### ISSUE TITLE
Open local files

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/audio#5]
Now that we have a somewhat functional player UI, we should probably set the app up to actually handle audio files.

If you open the app directly, just launch a file open dialog (since the UI is useless without a file chosen)

**Comment by cassidyjames** [comment]
[$25 bounty added](https://www.bountysource.com/issues/40936315-accept-local-files)

**Comment by m3ntalsp00n** [comment]
Were you thinking of this? https://github.com/m3ntalsp00n/audio

**Comment by cassidyjames** [comment]
@m3ntalsp00n ooh, I'll have to take a look!

**Comment by cassidyjames** [comment]
@m3ntalsp00n be sure to claim the bounty. :)

**Comment by m3ntalsp00n** [comment]
Sweet as. Should also address issue #3. 

Will need you to close the issue to claim.
